import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/footer/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="bg-gradient-to-br from-green-100 via-white to-green-100">
        {children}
      </body>
    </html>
  );
}
